### ISSUE TITLE
t/25-sitematrix.t started to fail

### ISSUE THREAD

**Issue by eserte** [MediaWiki-Bot/MediaWiki-Bot#108]
My smoker systems started to report the following failure:

```
#   Failed test 'db->domain OK'
#   at t/25-sitematrix.t line 27.
#     Structures begin differing at:
#          $got->[1] = undef
#     $expected->[1] = 'bat-smg.wikipedia.org'

#   Failed test 'domain->db OK'
#   at t/25-sitematrix.t line 43.
#     Structures begin differing at:
#          $got->[1] = 'sgswiki'
#     $expected->[1] = 'bat-smgwiki'
# Looks like you failed 2 tests of 4.
t/25-sitematrix.t .............. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/4 subtests 
```

Looking at http://matrix.cpantesters.org/?dist=MediaWiki-Bot%205.007000;reports=1#sl=7,1 it seems that this started in August 2023.

**Comment by Scott5114** [comment]
This seems to be failing because the Wikimedia Foundation is in the process of replacing the nonstandard `bat-smg` language code with the standard code `sgs` (see [this WMF Phabricator entry](https://phabricator.wikimedia.org/T27522) for details). Accordingly, replacing `bat-smgwiki` with `sgswiki` in `t/25-sitematrix.t` is enough to get the test to pass.

I'm not entirely sure why the test is pinging this wiki in particular, though, so I'm not sure if just updating the test is the Right Thing. It's possible that it was chosen because it has a hyphen in it, or perhaps because it was a nonstandard code. Someone more knowledgeable about wikis than me suggested using `cbk-zam` / `cbk_zamwiki` or `map-bms` / `map_bmswiki` instead.

**Comment by wp-seth** [comment]
thanks for reporting!

while i was fixing the test, i saw that in
https://github.com/MediaWiki-Bot/MediaWiki-Bot/blob/9532988d120530441195e7f2bd527846596f432d/lib/MediaWiki/Bot.pm#L3885
the url is not correct (anymore).

it should be
- https://noc.wikimedia.org/conf/dblists/closed.dblist

instead of
- http://noc.wikimedia.org/conf/closed.dblist

but, if i fix this, then test
https://github.com/MediaWiki-Bot/MediaWiki-Bot/blob/9532988d120530441195e7f2bd527846596f432d/t/25-sitematrix.t#L22
fails, because the wiki is closed. however it was me who added that test in https://github.com/MediaWiki-Bot/MediaWiki-Bot/commit/331c963da087c74809fe2b186cf23eac884c335b.
Haha!

However, i'll fix both now.
